name: Create a VPC & EKS Cluster for stage
on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{secret_AWS_ACCESS_KEY_ID}}
  AWS_SECRET_KEY_ID: ${{secret_AWS_SECRET_KEY_ID}}

job:
  deploy:
     run on : ubuntu-latest

     steps: 
       - name: checkout the code
         uses: actions/checkout@v4
        
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

       - name: Terraform init
         run : terraform init

       - name: Terraform plan
         run : terraform plan
       
       - name: Terraform apply
         run: terraform apply -auto-approve